nodeLinker: node-modules
enableGlobalCache: true

packageExtensions:
  "react-router-dom@*":
    peerDependencies:
      "@types/react": "*"
      "react": "*"
      "react-dom": "*"

ignoreEngines: true
installConfig:
  ignorePlatform: true 